### PR TITLE
Add functions

### PR DESCRIPTION
**Pull request by gitlichking**

### CODE REVIEW

**Review by mezgoodle — CHANGES_REQUESTED** [review]
Can you write in every image the _name of function_ as **header**?

**Comment by Dmytrenko-Roman** [comment]
> Can you write in every image the _name of function_ as **header**?

Denied.

**Comment by mezgoodle** [comment]
> > Can you write in every image the _name of function_ as **header**?
> 
> Denied.

Then rename files and commit it

**Comment by Dmytrenko-Roman** [comment]
> > > Can you write in every image the _name of function_ as **header**?
> > 
> > 
> > Denied.
> 
> Then rename files and commit it

I see only darkness before me...

**Comment by mezgoodle** [comment]
> > > > Can you write in every image the _name of function_ as **header**?
> > > 
> > > 
> > > Denied.
> > 
> > 
> > Then rename files and commit it
> 
> I see only darkness before me...

"Okey, then i close this PR and your commits will see only darkness" @Sylvanas

**Comment by mezgoodle** [comment]
> > > > > Can you write in every image the _name of function_ as **header**?
> > > > 
> > > > 
> > > > Denied.
> > > 
> > > 
> > > Then rename files and commit it
> > 
> > 
> > I see only darkness before me...
> 
> "Okey, then i close this PR and your commits will see only darkness" @Sylvanas

Lol, there is the user...

**Comment by Dmytrenko-Roman** [comment]
> > > > > Can you write in every image the _name of function_ as **header**?
> > > > 
> > > > 
> > > > Denied.
> > > 
> > > 
> > > Then rename files and commit it
> > 
> > 
> > I see only darkness before me...
> 
> "Okey, then i close this PR and your commits will see only darkness" @Sylvanas


Then I will go to Metarhia, take Metarhmorn from the block there and then you yourself know what will happen.

**Comment by mezgoodle** [comment]
> > > > > > Can you write in every image the _name of function_ as **header**?
> > > > > 
> > > > > 
> > > > > Denied.
> > > > 
> > > > 
> > > > Then rename files and commit it
> > > 
> > > 
> > > I see only darkness before me...
> > 
> > 
> > "Okey, then i close this PR and your commits will see only darkness" @Sylvanas
> 
> Then I will go to Metarhia, take Metarhmorn from the block there and then you yourself know what will happen.

Okey, but when you will rename files?

**Comment by mezgoodle** [comment]
Nice
Now please wait while I am reading you diagrams

**Comment by Dmytrenko-Roman** [comment]
> Nice
> Now please wait while I am reading you diagrams


Damn it, Uther!

**Review by mezgoodle — COMMENTED** [review]
**AuthorizedUserReview.png** has been successful reviewed

**Review by mezgoodle — COMMENTED** [review]
**AuthorizedUserCancel.png** has been successful review

**Review by mezgoodle — COMMENTED** [review]
AuthorizedUserOrderUpdates.png has been successfull reviewed

**Review by mezgoodle — APPROVED** [review]
Your change have been **approved**!

**Pull request merged**
