### PR TITLE
Mezgoodle functions

### PR DESCRIPTION
**Pull request by mezgoodle**
_GetUser_();
_Book_();
_CheckBookings_();
_Review_();

### CODE REVIEW

**Review by La7rodectus — CHANGES_REQUESTED** [review]
GetUser method have to have object type instead of void.

**Review by La7rodectus — CHANGES_REQUESTED** [review]
Same.

**Comment by mezgoodle** [comment]
So, to resolve conflict I deleted GetUser() function, if it disappear, we will just commit again into master

**Comment by mezgoodle** [comment]
Oh no, now also _GetRoom_, for what?

**Review by La7rodectus — APPROVED** [review]
All good

**Pull request merged**
