### PR TITLE
Functions-7-8-9

### PR DESCRIPTION
**Pull request by gitlichking**

### CODE REVIEW

**Review by mezgoodle — COMMENTED** [review]
Okey, first diagram is not bad, also look at my diagrams [here](https://github.com/mezidia/hotel-booking/tree/mezgoodle-functionality-patch/docs), maybe write errors like this

**Comment by Dmytrenko-Roman** [comment]
> Okey, first diagram is not bad, also look at my diagrams [here](https://github.com/mezidia/hotel-booking/tree/mezgoodle-functionality-patch/docs), maybe write errors like this

Ok.

**Review by mezgoodle — APPROVED** [review]
Okey, my review is over
Wait for @La7rodectus

**Review by La7rodectus — APPROVED** [review]
Everything is fine.

**Comment by mezgoodle** [comment]
Sorry, my bad, I merger pr from @ImgBotApp and file on _master_ has been changed, so there is conflict here. If you can, please commit your files directly to master and close this pull request

**Pull request merged**
