### PR TITLE
Add table of precedents

### PR DESCRIPTION
**Pull request by La7rodectus**

### CODE REVIEW

**Review by lizardlynx — APPROVED** [review]

**Review by mezgoodle — APPROVED** [review]
The diagram is great, but the inscription "admin" is poorly visible

**Comment by VsIG-official** [comment]
I think that You need to add one more option for "authorized user" - "Report comment"

**Comment by mezgoodle** [comment]
> I think that You need to add one more option for "authorized user" - "Report comment"

do we have it in [README](https://github.com/mezidia/hotel-booking/blob/master/README.md)?

**Comment by VsIG-official** [comment]
> > I think that You need to add one more option for "authorized user" - "Report comment"
> 
> do we have it in [README](https://github.com/mezidia/hotel-booking/blob/master/README.md)?

https://github.com/mezidia/hotel-booking/blob/master/README.md#authorized-users-can

**Review by VsIG-official — CHANGES_REQUESTED** [review]
*My comment above*

**Comment by mezgoodle** [comment]
> > > I think that You need to add one more option for "authorized user" - "Report comment"
> > 
> > 
> > do we have it in [README](https://github.com/mezidia/hotel-booking/blob/master/README.md)?
> 
> https://github.com/mezidia/hotel-booking/blob/master/README.md#authorized-users-can
> sixth

agree, my fault

**Comment by La7rodectus** [comment]
> I think that You need to add one more option for "authorized user" - "Report comment"

Solved

**Comment by La7rodectus** [comment]
> The diagram is great, but the inscription "admin" is poorly visible

Solved

**Pull request merged**
