### PR TITLE
Func-1-2-3

### PR DESCRIPTION
**Pull request by VsIG-official**

### CODE REVIEW

**Comment by VsIG-official** [comment]
My diagrams looks too easy, so, maybe, there're some problems with them

**Comment by mezgoodle** [comment]
> My diagrams looks too easy, so, maybe, there're some problems with them

this is not always the case

**Review by mezgoodle — CHANGES_REQUESTED** [review]
I think:
- in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/CheckForDeals.png) diagram should be exception about _non-existing_ id
- in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/CheckAvailableRooms.png) diagram write exception about **id** like above
- in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/SearchForInfo.png) diagram your exception is as result, but not as error, that will crush a program. You can write like that: "Search by parameters of a non-existent hotel"

**Comment by VsIG-official** [comment]
> I think:
> 
> * in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/CheckForDeals.png) diagram should be exception about _non-existing_ id
> * in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/CheckAvailableRooms.png) diagram write exception about **id** like above
> * in [this](https://github.com/mezidia/hotel-booking/blob/Func-1-2-3/docs/SearchForInfo.png) diagram your exception is as result, but not as error, that will crush a program. You can write like that: "Search by parameters of a non-existent hotel"

changed

**Review by mezgoodle — APPROVED** [review]

**Review by La7rodectus — CHANGES_REQUESTED** [review]
Hmm, it looks good, but somehow everything is two-block. You can just add in each case the process of sending information back to the user. In CheckForDeals case it seems to me that it doesn't work that way, every time the user opens the page with the ID of a certain hotel \ a request is sent to the database to display financial information about the hotel (also when searching by criteria) DB search for the new price or availability of special offers.

**Comment by VsIG-official** [comment]
> Hmm, it looks good, but somehow everything is two-block. You can just add in each case the process of sending information back to the user. In CheckForDeals case it seems to me that it doesn't work that way, every time the user opens the page with the ID of a certain hotel \ a request is sent to the database to display financial information about the hotel (also when searching by criteria) DB search for the new price or availability of special offers.

changed, but have some problems with this > a request is sent to the database to display financial information about the hotel **(also when searching by criteria)**. Just don't know where and what exactly to put in this diagram

**Review by La7rodectus — APPROVED** [review]
It is fine now.

**Pull request merged**
