### PR TITLE
Functionality 4-6

### PR DESCRIPTION
**Pull request by mezgoodle**

### CODE REVIEW

**Comment by mezgoodle** [comment]
All my images have been uploaded

**Review by La7rodectus — CHANGES_REQUESTED** [review]
Add exceptional situations.

**Comment by mezgoodle** [comment]
@La7rodectus , please, review my diagrams

**Comment by VsIG-official** [comment]
Well, if You have added two exeptions, than there is one more: the room may be taken, while user was making a request

**Comment by mezgoodle** [comment]
> Well, if You have added two exeptions, than there is one more: the room may be taken, while user was making a request [37bc0e4](https://github.com/mezidia/hotel-booking/commit/37bc0e41154b42416cfaf495f20455eace3a3f89)

denied

**Review by La7rodectus — APPROVED** [review]
Everything is fine.

**Pull request merged**
