### PR TITLE
add funcs 13+

### PR DESCRIPTION
**Pull request by lizardlynx**

### CODE REVIEW

**Review by mezgoodle — APPROVED** [review]
I think, everything is good, but required someone review

**Comment by VsIG-official** [comment]
In AdminChagePermissions.png I think, that need to specify **where** admin is clicking on "Change permission".
For example, "go to user profile" and then is changing permission

**Comment by VsIG-official** [comment]
AdminModerateContent.png looks good for Me

**Comment by VsIG-official** [comment]
same is for AdminSupport.png

**Comment by VsIG-official** [comment]
and AuthorizedUserUpdateInfo.png is fine too

**Review by VsIG-official — COMMENTED** [review]
*My comments above*

**Comment by lizardlynx** [comment]
> In AdminChagePermissions.png I think, that need to specify **where** admin is clicking on "Change permission".
> For example, "go to user profile" and then is changing permission

i thought it was not nessesary, but okay

**Review by La7rodectus — APPROVED** [review]
Looks good for me too.

**Pull request merged**
