### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lizardlynx**

### CODE REVIEW

**Review by La7rodectus — APPROVED** [review]
Excellent, fully reflects the essence of the relational model.

**Review by mezgoodle — COMMENTED** [review]
Great work!
Can you move arrows on _back ground_, **behind** the blocks?

**Comment by VsIG-official** [comment]
Does authorized user need an "age"?
Maybe booking needs to have an "owner" or it's implies by using arrows?
In "Authorized user" "age" can start with capital letter.
You can change some block sizes, 'cause they have some empty space.
And change arrows, 'cause all of them have different styles and unnecessary big bends/twists

**Comment by lizardlynx** [comment]
> Does authorized user need an "age"?
I used properties of database schema, so, I think it does.
> Maybe booking needs to have an "owner" or it's implies by using arrows?
Yes, I excluded every property, which is being displayed by arrows.
> In "Authorized user" "age" can start with capital letter.
Changed.
> You can change some block sizes, 'cause they have some empty space.
Changed.
> And change arrows, 'cause all of them have different styles and unnecessary big bends/twists
Changed.

**Comment by lizardlynx** [comment]
> Great work!
> Can you move arrows on _back ground_, **behind** the blocks?

Changed.

**Review by VsIG-official — APPROVED** [review]
Seems good to Me.
Firstly I thought, that You could place them even more closer and reduce the size of blocks, but then one idea has come to My mind, that the schema could look complicated. So You can experiment with this, if You want, but, as I said, seems good

**Review by mezgoodle — APPROVED** [review]
**Nice** diagram, even size is **excellent**!

**Comment by lizardlynx** [comment]
Thank you!

**Pull request merged**
